// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBOrswZWGZXJ_--kLH2NW1O8fWuIXre1F8',
    appId: '1:539438070232:web:564e453614672e1de3daad',
    messagingSenderId: '539438070232',
    projectId: 'foodapp-ac8e3',
    authDomain: 'foodapp-ac8e3.firebaseapp.com',
    storageBucket: 'foodapp-ac8e3.firebasestorage.app',
    measurementId: 'G-BL53QKTTN3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAGxfrSUE50gVZbV2jZ0r0vpAF8CixhUAo',
    appId: '1:539438070232:android:438b719da1d753a8e3daad',
    messagingSenderId: '539438070232',
    projectId: 'foodapp-ac8e3',
    storageBucket: 'foodapp-ac8e3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCYg_slLg56XYr3RFHu92IGzPTkt7oppyI',
    appId: '1:539438070232:ios:74e6851317e6a811e3daad',
    messagingSenderId: '539438070232',
    projectId: 'foodapp-ac8e3',
    storageBucket: 'foodapp-ac8e3.firebasestorage.app',
    iosBundleId: 'com.example.fotpulse',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCYg_slLg56XYr3RFHu92IGzPTkt7oppyI',
    appId: '1:539438070232:ios:74e6851317e6a811e3daad',
    messagingSenderId: '539438070232',
    projectId: 'foodapp-ac8e3',
    storageBucket: 'foodapp-ac8e3.firebasestorage.app',
    iosBundleId: 'com.example.fotpulse',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBOrswZWGZXJ_--kLH2NW1O8fWuIXre1F8',
    appId: '1:539438070232:web:be42ae7c8c6eddbae3daad',
    messagingSenderId: '539438070232',
    projectId: 'foodapp-ac8e3',
    authDomain: 'foodapp-ac8e3.firebaseapp.com',
    storageBucket: 'foodapp-ac8e3.firebasestorage.app',
    measurementId: 'G-XRJ1LTXH3E',
  );
}
